version: "3"
services:
  app:
    build: .
    ports:
      - "${PORT:-8889}:${PORT:-8889}"
    environment:
      - PORT=${PORT:-8889}
      - API_PORT=${API_PORT:-8888}
      - LOG_FILE=${LOG_FILE:-logger.log}
      - TOKEN_ISSUE_NAME=${TOKEN_ISSUE_NAME:-enigmacamp}
      - TOKEN_KEY=${TOKEN_KEY:-Gokkzzz!!}
      - TOKEN_LIFE_TIME=${TOKEN_LIFE_TIME:-1}
      - DB_NAME=${DB_NAME:-laundry.db}
